# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161106_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(default='UNDEFINED'),
            preserve_default=False,
        ),
    ]
